In [3]:
# Shree Gaayathri.V_ credit card fraud detection_Task 5
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
http://localhost:8888/notebooks/Untitled6.ipynb?kernel_name=python3#

#Loading the dataset 
credit_card_data = pd.read_csv(r"C:\Users\USER\Desktop\Internship_Codsoft\creditcard.csv")

#Print first 5 rows
print(credit_card_data.head())
print(credit_card_data.tail())      
 
#Dataset information
print(credit_card_data.info())

#Checking the missing values in each column
print(credit_card_data.isnull(http://localhost:8888/notebooks/Untitled6.ipynb?kernel_name=python3#).sum())

#Distrubution of legit transaction and fradulant transection
print(credit_card_data['Class'].value_counts)

#0----> Normal Transection
#1----> Fraudulant Transection

#Separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]   
print(legit.shape)
print(fraud.shape)
 
#Statistical measure of the data
print(legit.Amount.describe())
print(fraud.Amount.describe())

#Compare the values for both transactions
print(credit_card_data.groupby('Class').mean())

#Undersampling
legit_sample = legit.sample(n=492)

#Concatenating two DataFrames
new_dataset = pd.concat([legit_sample, fraud], axis=0)
print(new_dataset.head())
print(new_dataset.tail())

print(new_dataset['Class'].value_counts())

print(new_dataset.groupby('Class').mean())

#Splitting the data into Features & Targets
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']
print(X)
print(Y)

#Split the data into Training data & Testing Data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)
print(X.shape, X_train.shape, X_test.shape)

#Model Training
model = LogisticRegression()

# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

#Accuracy Score
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Accuracy on Training data : ', training_data_accuracy)

# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print('Accuracy score on Test Data : ', test_data_accuracy)

   Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010

        V26       V27       V28  Amount  Class
0 -0.189115  0.133558 -0.021053  149.62      0
1  0.125895 -0.008983  0.014724    2.69      0
2 -0.139097 -0.055353 -0.059752  378.66      0
3 -0.221929  0.062723  0.061458  123.50      0
4  0.502292  0.219422  0.215153   69.99      0

[5 rows x 31 columns]
            Time         V1         V2        V3        V4        V5  \
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546

              V6        V7        V8        V9  ...       V21       V22  \
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078

             V23       V24       V25       V26       V27       V28  Amount  \
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00

        Class
284802      0
284803      0
284804      0
284805      0
284806      0

[5 rows x 31 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB
None
Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64
<bound method IndexOpsMixin.value_counts of 0         0
1         0
2         0
3         0
4         0
         ..
284802    0
284803    0
284804    0
284805    0
284806    0
Name: Class, Length: 284807, dtype: int64>
(284315, 31)
(492, 31)
count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64
count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64
               Time        V1        V2        V3        V4        V5  \
Class
0      94838.202258  0.008258 -0.006271  0.012171 -0.007860  0.005453
1      80746.806911 -4.771948  3.623778 -7.033281  4.542029 -3.151225

             V6        V7        V8        V9  ...       V20       V21  \
Class                                          ...
0      0.002419  0.009637 -0.000987  0.004467  ... -0.000644 -0.001235
1     -1.397737 -5.568731  0.570636 -2.581123  ...  0.372319  0.713588

            V22       V23       V24       V25       V26       V27       V28  \
Class
0     -0.000024  0.000070  0.000182 -0.000072 -0.000089 -0.000295 -0.000131
1      0.014049 -0.040308 -0.105130  0.041449  0.051648  0.170575  0.075667

           Amount
Class
0       88.291022
1      122.211321

[2 rows x 30 columns]
            Time        V1        V2        V3        V4        V5        V6  \
76396    56545.0 -0.676060  0.177642  1.537934  0.283634 -1.724231 -0.188931
20406    31021.0 -4.064560  1.663548  0.701321 -1.899059  0.245438 -0.915223
252945  156035.0 -0.181718  1.734032 -2.114288  0.239167  1.383715 -1.388490
163450  115945.0  2.077221  0.153954 -1.940518  0.445150  0.504759 -1.506509
43321    41462.0 -0.653857  0.372777  0.910090  0.474636 -0.252508  0.063378

              V7        V8        V9  ...       V21       V22       V23  \
76396  -0.099836  0.593253  0.292456  ...  0.446146  0.834720  0.403467
20406   1.405746 -1.382548  2.642657  ... -0.499738  0.069992  0.275005
252945  1.122214  0.137393 -0.748350  ...  0.093820  0.257257 -0.209112
163450  0.821880 -0.586766  0.247272  ...  0.152776  0.706776 -0.088288
43321   1.613403 -0.093478 -0.990414  ...  0.277522  0.373501  0.260214

             V24       V25       V26       V27       V28  Amount  Class
76396   0.358068 -0.542832  0.365162 -0.115862  0.000279  171.50      0
20406   0.355147 -0.163053  0.474619 -1.921282 -0.785293    7.68      0
252945  0.467121 -0.431780  0.693601  0.032472  0.198954    0.76      0
163450  0.060041  0.569157 -0.069015 -0.045978 -0.071603   13.05      0
43321  -0.005315  0.380802 -0.375219 -0.044917  0.031050  245.08      0

[5 rows x 31 columns]
            Time        V1        V2        V3        V4        V5        V6  \
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V21       V22       V23  \
279863 -0.882850  0.697211 -2.064945  ...  0.778584 -0.319189  0.639419
280143 -1.413170  0.248525 -1.127396  ...  0.370612  0.028234 -0.145640
280149 -2.234739  1.210158 -0.652250  ...  0.751826  0.834108  0.190944
281144 -2.208002  1.058733 -1.632333  ...  0.583276 -0.269209 -0.456108
281674  0.223050 -0.068384  0.577829  ... -0.164350 -0.295135 -0.072173

             V24       V25       V26       V27       V28  Amount  Class
279863 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00      1
280143 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76      1
280149  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89      1
281144 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00      1
281674 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53      1

[5 rows x 31 columns]
0    492
1    492
Name: Class, dtype: int64
               Time        V1        V2        V3        V4        V5  \
Class
0      93121.556911  0.014934 -0.019898  0.036231 -0.001848 -0.004202
1      80746.806911 -4.771948  3.623778 -7.033281  4.542029 -3.151225

             V6        V7        V8        V9  ...       V20       V21  \
Class                                          ...
0     -0.065215 -0.028778 -0.010872  0.067258  ... -0.038303  0.023172
1     -1.397737 -5.568731  0.570636 -2.581123  ...  0.372319  0.713588

            V22       V23       V24       V25       V26       V27       V28  \
Class
0     -0.030077 -0.029657 -0.018699  0.037325  0.029504 -0.015885 -0.010910
1      0.014049 -0.040308 -0.105130  0.041449  0.051648  0.170575  0.075667

           Amount
Class
0       77.877195
1      122.211321

[2 rows x 30 columns]
            Time        V1        V2        V3        V4        V5        V6  \
76396    56545.0 -0.676060  0.177642  1.537934  0.283634 -1.724231 -0.188931
20406    31021.0 -4.064560  1.663548  0.701321 -1.899059  0.245438 -0.915223
252945  156035.0 -0.181718  1.734032 -2.114288  0.239167  1.383715 -1.388490
163450  115945.0  2.077221  0.153954 -1.940518  0.445150  0.504759 -1.506509
43321    41462.0 -0.653857  0.372777  0.910090  0.474636 -0.252508  0.063378
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
76396  -0.099836  0.593253  0.292456  ...  0.106017  0.446146  0.834720
20406   1.405746 -1.382548  2.642657  ...  0.069983 -0.499738  0.069992
252945  1.122214  0.137393 -0.748350  ... -0.200759  0.093820  0.257257
163450  0.821880 -0.586766  0.247272  ... -0.210143  0.152776  0.706776
43321   1.613403 -0.093478 -0.990414  ...  0.492419  0.277522  0.373501
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
76396   0.403467  0.358068 -0.542832  0.365162 -0.115862  0.000279  171.50
20406   0.275005  0.355147 -0.163053  0.474619 -1.921282 -0.785293    7.68
252945 -0.209112  0.467121 -0.431780  0.693601  0.032472  0.198954    0.76
163450 -0.088288  0.060041  0.569157 -0.069015 -0.045978 -0.071603   13.05
43321   0.260214 -0.005315  0.380802 -0.375219 -0.044917  0.031050  245.08
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]
76396     0
20406     0
252945    0
163450    0
43321     0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64
(984, 30) (787, 30) (197, 30)
Accuracy on Training data :  0.9263024142312579
Accuracy score on Test Data :  0.9086294416243654